package com.atomize.jpa.plus.datasource.provider;

import com.atomize.jpa.plus.datasource.enums.DatabaseType;
import com.atomize.jpa.plus.datasource.enums.DbType;
import com.atomize.jpa.plus.datasource.model.DataSourceDefinition;
import lombok.extern.slf4j.Slf4j;

import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

/**
 * 基于 JDBC 的数据源配置提供者
 *
 * <p>从数据库表中读取数据源配置，用户无需手动实现 {@link DataSourceProvider}。
 * 框架自动从主库的配置表中加载额外的数据源定义。</p>
 *
 * <h3>工作原理</h3>
 * <ol>
 *   <li>使用主数据源（Spring Boot {@code spring.datasource.*} 配置的数据源）连接数据库</li>
 *   <li>从 {@code jpa_plus_datasource}（可配置）表中查询所有已启用的数据源配置</li>
 *   <li>将查询结果映射为 {@link DataSourceDefinition} 列表返回</li>
 *   <li>支持自动建表（首次启动时，若表不存在则自动创建）</li>
 * </ol>
 *
 * <h3>表结构</h3>
 * <p>框架自动识别数据库类型（MySQL / PostgreSQL / Oracle / H2 等），
 * 使用对应方言创建配置表。表结构包含：</p>
 * <ul>
 *   <li>{@code name} —— 数据源名称（路由 key，如 "slave"、"analytics"）</li>
 *   <li>{@code db_type} —— 数据库类型（对应 {@link DatabaseType} 枚举名）</li>
 *   <li>{@code url} —— JDBC URL</li>
 *   <li>{@code username / password} —— 数据库账号密码</li>
 *   <li>{@code min_idle / max_pool_size / connection_timeout} —— 连接池参数</li>
 *   <li>{@code enabled} —— 是否启用（0=禁用, 1=启用）</li>
 * </ul>
 *
 * <h3>配置方式</h3>
 * <pre>{@code
 * jpa-plus:
 *   datasource:
 *     dynamic:
 *       enabled: true
 *       table-name: jpa_plus_datasource    # 配置表名（默认）
 *       auto-init-schema: true             # 自动建表（默认开启）
 * }</pre>
 *
 * <p><b>设计模式：</b>策略模式（Strategy） —— 作为 {@link DataSourceProvider} 的内置实现，
 * 用户可替换为自定义实现</p>
 *
 * @author guanxiangkai
 * @see DataSourceProvider
 * @see DatabaseType
 * @since 2026年03月25日 星期三
 */
@Slf4j
public class JdbcDataSourceProvider implements DataSourceProvider {

    /**
     * 查询已启用数据源配置的 SQL 模板
     */
    private static final String QUERY_TEMPLATE =
            "SELECT name, db_type, url, username, password, min_idle, max_pool_size, connection_timeout FROM %s WHERE enabled = 1";
    private static final String MYSQL_DDL = """
            CREATE TABLE IF NOT EXISTS %s (
                id          BIGINT AUTO_INCREMENT PRIMARY KEY,
                name        VARCHAR(64)  NOT NULL COMMENT '数据源名称（路由 key）',
                db_type     VARCHAR(32)  NOT NULL COMMENT '数据库类型（对应 DatabaseType 枚举）',
                url         VARCHAR(512) NOT NULL COMMENT 'JDBC URL',
                username    VARCHAR(128) NOT NULL COMMENT '数据库用户名',
                password    VARCHAR(256) NOT NULL COMMENT '数据库密码',
                min_idle    INT          DEFAULT 5     COMMENT '最小空闲连接数',
                max_pool_size INT        DEFAULT 20    COMMENT '最大连接池大小',
                connection_timeout BIGINT DEFAULT 30000 COMMENT '连接超时（毫秒）',
                enabled     TINYINT(1)   DEFAULT 1     COMMENT '是否启用（0=禁用, 1=启用）',
                create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                update_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                remark      VARCHAR(256)               COMMENT '备注',
                UNIQUE KEY uk_name (name)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='JPA-Plus 动态数据源配置表'
            """;
    private static final String POSTGRESQL_DDL = """
            CREATE TABLE IF NOT EXISTS %s (
                id          BIGSERIAL    PRIMARY KEY,
                name        VARCHAR(64)  NOT NULL UNIQUE,
                db_type     VARCHAR(32)  NOT NULL,
                url         VARCHAR(512) NOT NULL,
                username    VARCHAR(128) NOT NULL,
                password    VARCHAR(256) NOT NULL,
                min_idle    INT          DEFAULT 5,
                max_pool_size INT        DEFAULT 20,
                connection_timeout BIGINT DEFAULT 30000,
                idle_timeout BIGINT      DEFAULT 600000,
                max_lifetime BIGINT      DEFAULT 1800000,
                enabled     SMALLINT     DEFAULT 1,
                create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                update_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                remark      VARCHAR(256)
            )
            """;

    // ─── DDL 模板（按数据库方言） ───
    private static final String ORACLE_DDL = """
            CREATE TABLE %s (
                id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name        VARCHAR2(64)  NOT NULL UNIQUE,
                db_type     VARCHAR2(32)  NOT NULL,
                url         VARCHAR2(512) NOT NULL,
                username    VARCHAR2(128) NOT NULL,
                password    VARCHAR2(256) NOT NULL,
                min_idle    NUMBER        DEFAULT 5,
                max_pool_size NUMBER      DEFAULT 20,
                connection_timeout NUMBER DEFAULT 30000,
                idle_timeout NUMBER      DEFAULT 600000,
                max_lifetime NUMBER      DEFAULT 1800000,
                enabled     NUMBER(1)     DEFAULT 1,
                create_time TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                update_time TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                remark      VARCHAR2(256)
            )
            """;
    private static final String GENERIC_DDL = """
            CREATE TABLE IF NOT EXISTS %s (
                id          BIGINT AUTO_INCREMENT PRIMARY KEY,
                name        VARCHAR(64)  NOT NULL UNIQUE,
                db_type     VARCHAR(32)  NOT NULL,
                url         VARCHAR(512) NOT NULL,
                username    VARCHAR(128) NOT NULL,
                password    VARCHAR(256) NOT NULL,
                min_idle    INT          DEFAULT 5,
                max_pool_size INT        DEFAULT 20,
                connection_timeout BIGINT DEFAULT 30000,
                idle_timeout BIGINT      DEFAULT 600000,
                max_lifetime BIGINT      DEFAULT 1800000,
                enabled     INT          DEFAULT 1,
                create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                update_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                remark      VARCHAR(256)
            )
            """;
    private final DataSource configDataSource;
    private final String tableName;

    /**
     * @param configDataSource 主数据源（用于读取配置表）
     * @param tableName        配置表名
     * @param autoInitSchema   是否自动建表
     */
    public JdbcDataSourceProvider(DataSource configDataSource, String tableName, boolean autoInitSchema) {
        this.configDataSource = Objects.requireNonNull(configDataSource, "configDataSource must not be null");
        this.tableName = Objects.requireNonNull(tableName, "tableName must not be null");

        if (autoInitSchema) {
            initSchema();
        }
    }

    @Override
    public List<DataSourceDefinition> provide() {
        String sql = QUERY_TEMPLATE.formatted(tableName);
        List<DataSourceDefinition> definitions = new ArrayList<>();

        try (Connection conn = configDataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                definitions.add(mapRow(rs));
            }
            log.debug("Loaded {} datasource definition(s) from table '{}'", definitions.size(), tableName);

        } catch (SQLException e) {
            log.error("Failed to load datasource definitions from table '{}': {}", tableName, e.getMessage(), e);
        }

        return List.copyOf(definitions);
    }

    // ─── 内部方法 ───

    /**
     * 将 ResultSet 行映射为 DataSourceDefinition
     */
    private DataSourceDefinition mapRow(ResultSet rs) throws SQLException {
        return new DataSourceDefinition(
                rs.getString("name"),
                resolveDbType(rs.getString("db_type")),
                rs.getString("url"),
                rs.getString("username"),
                rs.getString("password"),
                null,                               // driverClassName — 由 dbType 自动推导
                rs.getInt("min_idle"),
                rs.getInt("max_pool_size"),
                rs.getLong("connection_timeout"),
                rs.getLong("idle_timeout"),
                rs.getLong("max_lifetime"),
                null,                               // poolName — 自动生成
                null                                // connectionTestQuery — 由 dbType 自动推导
        );
    }

    /**
     * 根据字符串名称解析 {@link DbType}
     *
     * @param dbTypeName 数据库类型名（如 "MYSQL"、"POSTGRESQL"）
     * @return 对应的 DbType 实例
     * @throws IllegalArgumentException 不支持的类型
     */
    private DbType resolveDbType(String dbTypeName) {
        try {
            return DatabaseType.valueOf(dbTypeName.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException(
                    "Unsupported database type: '%s'. Supported types: %s".formatted(
                            dbTypeName, Arrays.toString(DatabaseType.values())));
        }
    }

    /**
     * 自动建表（检测数据库方言，使用对应 DDL）
     */
    private void initSchema() {
        try (Connection conn = configDataSource.getConnection()) {
            if (tableExists(conn)) {
                log.debug("Table '{}' already exists, skip schema initialization", tableName);
                return;
            }
            String ddl = selectDDL(conn);
            try (Statement stmt = conn.createStatement()) {
                stmt.execute(ddl);
                log.info("Table '{}' created successfully", tableName);
            }
        } catch (SQLException e) {
            log.warn("Failed to auto-init schema for table '{}': {}", tableName, e.getMessage(), e);
        }
    }

    /**
     * 检测配置表是否已存在
     */
    private boolean tableExists(Connection conn) throws SQLException {
        DatabaseMetaData meta = conn.getMetaData();
        // 尝试原始表名
        try (ResultSet rs = meta.getTables(null, null, tableName, new String[]{"TABLE"})) {
            if (rs.next()) return true;
        }
        // 尝试大写（Oracle 等数据库默认大写存储）
        try (ResultSet rs = meta.getTables(null, null, tableName.toUpperCase(), new String[]{"TABLE"})) {
            return rs.next();
        }
    }

    /**
     * 根据数据库产品名选择对应方言的 DDL
     */
    private String selectDDL(Connection conn) throws SQLException {
        String product = conn.getMetaData().getDatabaseProductName().toUpperCase();
        return switch (product) {
            case String s when s.contains("POSTGRESQL") -> POSTGRESQL_DDL.formatted(tableName);
            case String s when s.contains("ORACLE") -> ORACLE_DDL.formatted(tableName);
            case String s when s.contains("MYSQL") || s.contains("MARIADB") -> MYSQL_DDL.formatted(tableName);
            case String s when s.contains("H2") -> GENERIC_DDL.formatted(tableName);
            default -> {
                log.warn("Unknown database product '{}', using generic DDL", product);
                yield GENERIC_DDL.formatted(tableName);
            }
        };
    }
}

