package com.actomize.jpa.plus.field.dict.provider;

import com.actomize.jpa.plus.field.dict.model.DictTranslateItem;
import com.actomize.jpa.plus.field.dict.spi.DictProvider;
import lombok.extern.slf4j.Slf4j;

import javax.sql.DataSource;
import java.sql.*;
import java.util.*;
import java.util.regex.Pattern;

/**
 * 基于 JDBC 的字典数据提供者
 *
 * <p>从数据库表中读取字典数据，用户无需手动实现 {@link DictProvider}。
 * 框架自动从主库的字典表中加载字典项。</p>
 *
 * <h3>工作原理</h3>
 * <ol>
 *   <li>使用主数据源（Spring Boot {@code spring.datasource.*} 配置的数据源）连接数据库</li>
 *   <li>从 {@code jpa_plus_dict}（可配置）表中查询指定 dict_code 的所有已启用字典项</li>
 *   <li>将查询结果映射为 {@link DictTranslateItem} 列表返回</li>
 *   <li>支持自动建表（首次启动时，若表不存在则自动创建）</li>
 * </ol>
 *
 * <h3>表结构</h3>
 * <p>框架自动识别数据库类型（MySQL / PostgreSQL / Oracle / H2 等），
 * 使用对应方言创建字典表。表结构包含：</p>
 * <ul>
 *   <li>{@code dict_code} —— 字典类型编码（如 "sys_user_sex"）</li>
 *   <li>{@code dict_value} —— 字典值</li>
 *   <li>{@code dict_label} —— 字典标签（前端展示用）</li>
 *   <li>{@code dict_type} —— 字典项样式类型（如 primary / success / warning 等 Tag 颜色）</li>
 *   <li>{@code sort} —— 排序号</li>
 *   <li>{@code enabled} —— 是否启用（0=禁用, 1=启用）</li>
 * </ul>
 *
 * <h3>配置方式</h3>
 * <pre>{@code
 * jpa-plus:
 *   dict:
 *     jdbc:
 *       enabled: true                      # 启用 JDBC 字典提供者（默认 false）
 *       table-name: jpa_plus_dict          # 字典表名（默认）
 *       auto-init-schema: true             # 自动建表（默认开启）
 * }</pre>
 *
 * <p><b>设计模式：</b>策略模式（Strategy） —— 作为 {@link DictProvider} 的内置实现，
 * 用户可替换为自定义实现</p>
 *
 * @author guanxiangkai
 * @see DictProvider
 * @see DictTranslateItem
 * @since 2026年03月26日 星期四
 */
@Slf4j
public class JdbcDictProvider implements DictProvider {

    /**
     * 查询已启用字典项的 SQL 模板（按 sort 排序）
     */
    private static final String QUERY_TEMPLATE =
            "SELECT dict_code, dict_value, dict_label, dict_type, sort FROM %s WHERE dict_code = ? AND enabled = 1 ORDER BY sort";
    private static final String MYSQL_DDL = """
            CREATE TABLE IF NOT EXISTS %s (
                id          BIGINT AUTO_INCREMENT PRIMARY KEY,
                dict_code   VARCHAR(128) NOT NULL COMMENT '字典类型编码',
                dict_value  VARCHAR(256) NOT NULL COMMENT '字典值',
                dict_label  VARCHAR(256) NOT NULL COMMENT '字典标签',
                dict_type   VARCHAR(64)  DEFAULT '' COMMENT '样式类型（primary/success/warning/danger/info）',
                sort        INT          DEFAULT 0  COMMENT '排序号',
                enabled     TINYINT(1)   DEFAULT 1  COMMENT '是否启用（0=禁用, 1=启用）',
                create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                update_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                remark      VARCHAR(256)            COMMENT '备注',
                INDEX idx_dict_code (dict_code)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='JPA-Plus 字典数据表'
            """;
    private static final String POSTGRESQL_DDL = """
            CREATE TABLE IF NOT EXISTS %s (
                id          BIGSERIAL    PRIMARY KEY,
                dict_code   VARCHAR(128) NOT NULL,
                dict_value  VARCHAR(256) NOT NULL,
                dict_label  VARCHAR(256) NOT NULL,
                dict_type   VARCHAR(64)  DEFAULT '',
                sort        INT          DEFAULT 0,
                enabled     SMALLINT     DEFAULT 1,
                create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                update_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                remark      VARCHAR(256)
            );
            CREATE INDEX IF NOT EXISTS idx_%s_dict_code ON %s (dict_code)
            """;

    // ─── DDL 模板（按数据库方言） ───
    private static final String ORACLE_DDL = """
            CREATE TABLE %s (
                id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                dict_code   VARCHAR2(128) NOT NULL,
                dict_value  VARCHAR2(256) NOT NULL,
                dict_label  VARCHAR2(256) NOT NULL,
                dict_type   VARCHAR2(64)  DEFAULT '',
                sort        NUMBER        DEFAULT 0,
                enabled     NUMBER(1)     DEFAULT 1,
                create_time TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                update_time TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                remark      VARCHAR2(256)
            )
            """;
    private static final String GENERIC_DDL = """
            CREATE TABLE IF NOT EXISTS %s (
                id          BIGINT AUTO_INCREMENT PRIMARY KEY,
                dict_code   VARCHAR(128) NOT NULL,
                dict_value  VARCHAR(256) NOT NULL,
                dict_label  VARCHAR(256) NOT NULL,
                dict_type   VARCHAR(64)  DEFAULT '',
                sort        INT          DEFAULT 0,
                enabled     INT          DEFAULT 1,
                create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                update_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                remark      VARCHAR(256)
            )
            """;
    /**
     * Allowlist pattern for table names — prevents SQL injection via tableName.
     */
    private static final Pattern SAFE_TABLE_NAME = Pattern.compile("^[a-zA-Z][a-zA-Z0-9_]*$");
    private final DataSource dataSource;
    private final String tableName;

    /**
     * @param dataSource     数据源（用于读取字典表）
     * @param tableName      字典表名
     * @param autoInitSchema 是否自动建表
     */
    public JdbcDictProvider(DataSource dataSource, String tableName, boolean autoInitSchema) {
        this.dataSource = Objects.requireNonNull(dataSource, "dataSource must not be null");
        Objects.requireNonNull(tableName, "tableName must not be null");
        // P0-14: Validate tableName against an allowlist to prevent SQL injection.
        if (!SAFE_TABLE_NAME.matcher(tableName).matches()) {
            throw new IllegalArgumentException(
                    "Invalid dict tableName '" + tableName + "'. " +
                            "Table names must match ^[a-zA-Z][a-zA-Z0-9_]*$ to prevent SQL injection.");
        }
        this.tableName = tableName;

        if (autoInitSchema) {
            initSchema();
        }
    }

    @Override
    public List<DictTranslateItem> getItems(String dictCode) {
        String sql = QUERY_TEMPLATE.formatted(tableName);
        List<DictTranslateItem> items = new ArrayList<>();

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, dictCode);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    items.add(mapRow(rs));
                }
            }
            log.debug("Loaded {} dict item(s) for dictCode '{}'", items.size(), dictCode);

        } catch (SQLException e) {
            log.error("Failed to load dict items for dictCode '{}' from table '{}': {}",
                    dictCode, tableName, e.getMessage(), e);
        }

        return List.copyOf(items);
    }

    @Override
    public Map<String, String> getLabels(String dictCode, Set<String> values) {
        if (values == null || values.isEmpty()) {
            return Map.of();
        }
        String placeholders = String.join(",", java.util.Collections.nCopies(values.size(), "?"));
        String sql = "SELECT dict_value, dict_label FROM %s WHERE dict_code = ? AND enabled = 1 AND dict_value IN (%s)"
                .formatted(tableName, placeholders);
        Map<String, String> labels = new LinkedHashMap<>();
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, dictCode);
            int idx = 2;
            for (String value : values) {
                ps.setString(idx++, value);
            }
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    labels.put(rs.getString("dict_value"), rs.getString("dict_label"));
                }
            }
        } catch (SQLException e) {
            log.error("Failed to batch load dict labels for dictCode '{}' from table '{}': {}",
                    dictCode, tableName, e.getMessage(), e);
        }
        return Map.copyOf(labels);
    }

    // ─── 内部方法 ───

    /**
     * 将 ResultSet 行映射为 DictTranslateItem
     */
    private DictTranslateItem mapRow(ResultSet rs) throws SQLException {
        return new DictTranslateItem(
                rs.getString("dict_code"),
                rs.getString("dict_value"),
                rs.getString("dict_label"),
                rs.getString("dict_type"),
                rs.getInt("sort")
        );
    }

    /**
     * 自动建表（检测数据库方言，使用对应 DDL）
     */
    private void initSchema() {
        try (Connection conn = dataSource.getConnection()) {
            if (tableExists(conn)) {
                log.debug("Table '{}' already exists, skip schema initialization", tableName);
                return;
            }
            String ddl = selectDDL(conn);
            try (Statement stmt = conn.createStatement()) {
                stmt.execute(ddl);
                log.info("Dict table '{}' created successfully", tableName);
            }
        } catch (SQLException e) {
            log.warn("Failed to auto-init schema for dict table '{}': {}", tableName, e.getMessage(), e);
        }
    }

    /**
     * 检测字典表是否已存在
     */
    private boolean tableExists(Connection conn) throws SQLException {
        DatabaseMetaData meta = conn.getMetaData();
        // 尝试原始表名
        try (ResultSet rs = meta.getTables(null, null, tableName, new String[]{"TABLE"})) {
            if (rs.next()) return true;
        }
        // 尝试大写（Oracle 等数据库默认大写存储）
        try (ResultSet rs = meta.getTables(null, null, tableName.toUpperCase(), new String[]{"TABLE"})) {
            return rs.next();
        }
    }

    /**
     * 根据数据库产品名选择对应方言的 DDL
     */
    private String selectDDL(Connection conn) throws SQLException {
        String product = conn.getMetaData().getDatabaseProductName().toUpperCase();
        return switch (product) {
            case String s when s.contains("POSTGRESQL") -> POSTGRESQL_DDL.formatted(tableName, tableName, tableName);
            case String s when s.contains("ORACLE") -> ORACLE_DDL.formatted(tableName);
            case String s when s.contains("MYSQL") || s.contains("MARIADB") -> MYSQL_DDL.formatted(tableName);
            case String s when s.contains("H2") -> GENERIC_DDL.formatted(tableName);
            default -> {
                log.warn("Unknown database product '{}', using generic DDL for dict table", product);
                yield GENERIC_DDL.formatted(tableName);
            }
        };
    }
}
